import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Bell,
  BriefcaseMedical,
  Circle,
  Brain,
  ChevronRight,
  Check,
  CheckCircle2,
  CheckSquare,
  CircleDot,
  CircleHelp,
  CircleX,
  CloudUpload,
  CreditCard,
  Droplet,
  Dumbbell,
  EyeOff,
  ExternalLink,
  Eye,
  FileText,
  FlaskConical,
  Hourglass,
  ImageIcon,
  Info,
  LayoutDashboard,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MessageSquare,
  MessageSquareText,
  Minus,
  Package,
  PackageCheck,
  Pencil,
  Pill,
  PillBottle,
  Plus,
  RefreshCw,
  Route,
  Scale,
  Search,
  ShoppingBag,
  ShoppingCart,
  ShieldCheck,
  Smartphone,
  Square,
  SquarePen,
  Star,
  Store,
  Syringe,
  Tag,
  Tags,
  Trash2,
  TriangleAlert,
  Truck,
  Undo2,
  User,
  UserPlus,
  Users,
  Verified,
  X,
} from "lucide-react";

const ICON_MAP = Object.freeze({
  dashboard: LayoutDashboard,
  inventory_2: Package,
  inventory: PackageCheck,
  category: Tags,
  branding_watermark: BadgeCheck,
  shopping_bag: ShoppingBag,
  autorenew: RefreshCw,
  payments: CreditCard,
  dynamic_form: FileText,
  route: Route,
  group: Users,
  storefront: Store,
  logout: LogOut,
  notifications: Bell,
  add: Plus,
  person_add: UserPlus,
  search: Search,
  image: ImageIcon,
  edit: Pencil,
  edit_note: SquarePen,
  delete: Trash2,
  close: X,
  hourglass_top: Hourglass,
  sync: RefreshCw,
  check_circle: CheckCircle2,
  local_shipping: Truck,
  cancel: CircleX,
  undo: Undo2,
  radio_button_checked: CircleDot,
  check_box: CheckSquare,
  check_box_outline_blank: Square,
  monitor_weight: Scale,
  medication: Pill,
  credit_card: CreditCard,
  sms: MessageSquareText,
  info: Info,
  open_in_new: ExternalLink,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  chevron_right: ChevronRight,
  help: CircleHelp,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  preview: Eye,
  description: FileText,
  visibility: Eye,
  visibility_off: EyeOff,
  medical_services: BriefcaseMedical,
  video_call: BriefcaseMedical,
  lab_research: FlaskConical,
  sell: Tag,
  verified_user: Verified,
  security: ShieldCheck,
  lock: Lock,
  fitness_center: Dumbbell,
  psychology: Brain,
  done_all: CheckCircle2,
  water_drop: Droplet,
  vaccines: Syringe,
  syringe: Syringe,
  prescriptions: PillBottle,
  local_pharmacy: PillBottle,
  support_agent: MessageSquareText,
  science: FlaskConical,
  schedule: Hourglass,
  person: User,
  receipt_long: FileText,
  chat: MessageSquare,
  mail: Mail,
  warning: TriangleAlert,
  error: TriangleAlert,
  error_outline: TriangleAlert,
  star: Star,
  check: Check,
  circle: Circle,
  shopping_cart: ShoppingCart,
  add_shopping_cart: ShoppingCart,
  remove: Minus,
  clinical_notes: FileText,
  login: LogIn,
  phone_iphone: Smartphone,
  cloud_upload: CloudUpload,
  pending: Hourglass,
});

export default function AppIcon({
  name,
  className = "",
  strokeWidth = 2,
  fallback = "help",
}) {
  const Icon = ICON_MAP[String(name || "").trim()] || ICON_MAP[fallback] || CircleHelp;
  return (
    <Icon
      aria-hidden="true"
      className={className}
      size="1em"
      strokeWidth={strokeWidth}
    />
  );
}
